
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
export const UPDATE_ALL_ITEMS = 'UPDATE_ALL_ITEMS';
export const UPDATE_ALL_ITEMS_DECREASE_QUANTITY= 'UPDATE_ALL_ITEMS_DECREASE_QUANTITY';
export const SET_CURRENT_USER_CART = 'SET_CURRENT_USER_CART';
export const INPROGRESS = 'INPROGRESS';
export const INPROGRESS_ADD_ITEM = 'INPROGRESS_ADD_ITEM';